stale-changes: do not fail if there is no specfile present at all stale-changes: allow extra changes files if listed as source in a spec

diff --git a/45-stale-changes b/45-stale-changes
--- a/45-stale-changes
+++ b/45-stale-changes
@@ -11,6 +11,7 @@ RETURN=0
 test "$VERBOSE" = true && echo -n "- checking for stale or missing changes "
 SPECLIST=`/usr/lib/osc/source_validators/helpers/output_versions -q -m $DIR_TO_CHECK | sed -e "s@ .*@@" | sort -u`
 
+test -n "$SPECLIST" && {
 for i in $SPECLIST ; do
     test -f $DIR_TO_CHECK/$i.changes || {
 	echo "WARNING: $i.changes does not exist. This package can not be submitted to openSUSE product projects."
@@ -26,10 +27,13 @@ for i in $DIR_TO_CHECK/*.changes ; do
         test "$pack" = "$N" && OKAY=1
     done
     if test $OKAY = 0 ; then
-	echo "ERROR: $(basename $i) not a subpackage, please remove"
-	RETURN=1
+	if ! grep -q "^Source[0-9]*:.*$N.changes" $DIR_TO_CHECK/*.spec ; then
+	    echo "ERROR: $(basename $i) not a subpackage, please remove"
+	    RETURN=1
+	fi
     fi
 done
+}
 test "$VERBOSE" = true && echo done
 
 
